trigger:
  branches:
    include:
      - main

pr:
  branches:
    include:
      - main

variables:
  output: "NO_OUTPUT"
  vmImageName: 'ubuntu-latest'
  vmImageName1: 'windows-2022'

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: First
  # condition: ne(variables.part, 'databricks')
  displayName: Stage
  dependsOn: []
  jobs:
  - job: First_job
    pool:
      vmImage: ubuntu-latest
    steps:
    - bash: |
        echo "Databricks part"
        echo "a"
        echo $(Build.SourceBranch)
        echo $(Build.SourceBranchName)
        echo $(System.PullRequest.SourceBranch)
        echo $(System.PullRequest.TargetBranch)

- stage: Build_docker
  # condition: ne(variables.part, 'azure_functions')
  displayName: Build the Docker image
  dependsOn: []
  jobs:
  - job: build_docker_image
    displayName: Build the Docker image
    timeoutInMinutes: 0
    condition: ne(variables.ms_hosted_agent, 'ubuntu')
    steps:
    - bash: |
        echo "Azure functions part"
        echo "a"
        echo $(ms_hosted_agent)
        echo "$(ms_hosted_agent)"

  - job: build_docker_image_hosted
    displayName: Build the Docker image
    timeoutInMinutes: 0
    pool:
      vmImage: ${{ variables.vmImageName1 }}
    condition: eq(variables.ms_hosted_agent, 'ubuntu')
    steps:
    - bash: |
        echo "Azure functions part"
        echo "a"
        echo $(ms_hosted_agent)
        echo "$(ms_hosted_agent)"
