trigger: none

pr: none

variables:
  output: "NO_OUTPUT"
  
stages:
- stage: First
  displayName: Stage
  jobs:
  - job: First_job
    pool:
      vmImage: ubuntu-latest
    steps:
    - bash: |
        echo "part = databricks"
        echo "Here we go"
        echo $(part)
        echo $(cluster_size)
        echo "a"
        if [ ! -z "$(cluster_size)" ]; then
          echo "$(cluster_size)"
        fi
      condition: eq(variables.part, 'databricks')

    - bash: |
        echo "part != databricks"
        echo "a"
      condition: ne(variables.part, 'databricks')

    - bash: |
        echo "Not existing variable equals databricks"
        echo "a"
      condition: eq(variables.parti, 'databricks')

    - bash: |
        echo "Not existing variable doesn't equal databricks"
        echo "a"
      condition: ne(variables.parti, 'databricks')      