trigger: none

pr: none

variables:
  output: "NO_OUTPUT"
  check_if_works: "NOT changed"
  
stages:
- stage: First
  displayName: Stage
  jobs:
  - job: First_job
    pool:
      vmImage: ubuntu-latest
    steps:
    - bash: |
        echo "Here we go"
        echo $(output)
        echo $(check_if_works)
        echo $[variables.check_if_works]

