trigger: none

pr: none

variables:
  output: "NO_OUTPUT"
  vmImageName: 'ubuntu-latest'
  vmImageName1: 'windows-2022'
  isMain: $[eq(variables['ms_hosted_agent'], 'true')]

stages:
- stage: First
  condition: ne(variables.part, 'databricks')
  displayName: Stage
  dependsOn: []
  jobs:
  - job: First_job
    pool:
      vmImage: ubuntu-latest
    steps:
    - bash: |
        echo "Databricks part"
        echo "a"

- stage: Build_docker
  condition: ne(variables.part, 'azure_functions')
  displayName: Build the Docker image
  dependsOn: []
  jobs:
  - job: build_docker_image
    displayName: Build the Docker image
    timeoutInMinutes: 0
    pool:
      ${{ if ne(variables['isMain'], true) }}:
        vmImage: ${{ variables.vmImageName1 }}
      ${{ if eq(variables['isMain'], true) }}:
        vmImage: ${{ variables.vmImageName }}
    steps:
    - bash: |
        echo "Azure functions part"
        echo "a"
        echo $(isMain)
        echo $(ms_hosted_agent)
        echo "$(ms_hosted_agent)"
