trigger: none

pr: none

variables:
  output: "NO_OUTPUT"
  
stages:
- stage: First
  displayName: Stage
  jobs:
  - job: First_job
    pool:
      vmImage: ubuntu-latest
    steps:
    - bash: |
        echo "Here we go"
        echo $(output)
        if [ ! -z ${check_if_works+x} ]; then
          echo "$(check_if_works)"
          echo "ssssss"
          echo "$check_if_works 1"
          echo "${check_if_works} 2"
          if [ "$(check_if_works)" = "IT WORKS" ]; then
            echo "HOORAY"
          fi
        fi

