# Python Function App to Linux on Azure
# Build a Python function app and deploy it to Azure as a Linux function app.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger: none

pr: none

variables:
  SlotName: 'ecpfr-uat'
  vmImageName: 'ubuntu-latesti'
  AgentsPoolName: TEST
  workingDirectory: '$(System.DefaultWorkingDirectory)/src/ecpfr/project'

pool:
  name: $(AgentsPoolName)

stages:
- stage: Build_docker
  displayName: Build the Docker image
  jobs:
  - job: build_docker_image
    displayName: Build the Docker image
    steps:
    - script: |
        set -o errexit
        agent_ip=`curl https://ipinfo.io/ip ; echo`
        echo "##vso[task.setvariable variable=AgentIP]$agent_ip"
    
#    - task: DeleteFiles@1
#      displayName: 'Remove unneeded files'
#      inputs:
#        sourceFolder: $(workingDirectory)
#        contents: '*'
#        removeSourceFolder: true
    
#    - task: AzureCLI@2
#      displayName: Add the agent to the firewall rules
#      inputs:
#        azureSubscription: playground-connection
#        scriptType: bash
#        scriptLocation: inlineScript
#        inlineScript: |
#          # az acr network-rule add -n $(ContainerRegistryName) --ip-address $(AgentIP)
#          az acr network-rule add -n acrlaunchtestvlad --ip-address $(AgentIP)
    
    - task: Docker@2
      displayName: Login to ACR
      inputs:
        command: login
        containerRegistry: playground-docker

    - script: |
        docker login acrlaunchtestvlad.azurecr.io --username 7fe32dfd-4b2e-488b-ad16-daf29a9405dc --password _mx7Q~VKHoG1qZ_diiMrVkGNrVHZ5xCp_gcX2
        # docker login $(ContainerRegistryName).azurecr.io --username $(az-sp-extended-devops-app-ja-03ut-ID) --password $(az-sp-extended-devops-app-ja-03ut-KEY)
    
    - task: Docker@2
      displayName: Build the image
      inputs:
        command: build
        repository: test
        tags: |
          test
    
    - task: Docker@2
      displayName: Push the image
      inputs:
        command: push
        repository: test
        tags: |
          test

    - task: Docker@2
      displayName: Logout of ACR
      inputs:
        command: logout
        containerRegistry: playground-docker
            
 #   - task: AzureCLI@2
 #     displayName: Remove the agent from the firewall rules
 #     condition: always()
 #     inputs:
 #       azureSubscription: playground-connection
 #       scriptType: bash
 #       scriptLocation: inlineScript
 #       inlineScript: |
 #         az acr network-rule remove -n acrlaunchtestvlad --ip-address $(AgentIP)
