name: P&G Continuous Winning

on:
  pull_request_target: # will always use the workflow definition from master/main, not your PR!
  push:
    branches:
      - main

jobs:
  checks:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - "3.9"
        package-extras:
          - devel
          #- "devel,spark,statsmodels,sklearn,lgbm,optuna,xarray"
    steps:
      # Do not remove: useful for debug purposes
      - name: Dump event JSON and environment
        run: cat "$GITHUB_EVENT_PATH"; env

      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0

      # Enable Python for your testing
      - name: Enable Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Configure Azure Artifacts
        run: |
          set -e
          pip install pip==21.2.4 keyring artifacts-keyring
          echo "PIP_EXTRA_INDEX_URL=${{ secrets.AZURE_ARTIFACTS_URL }}" >> $GITHUB_ENV

      - name: Install Python Dependencies
        run: |
          # set -e
          # pip install -r requirements.txt
          # pip install -r requirements-devel.txt
          # pip install -r requirements-spark.txt
          set -e
          pip install -r requirements.txt
          pip install -r requirements-devel.txt
          pip install -r requirements-orch.txt

      # Now install the Python package itself
      - name: Run tests
        run: |
          pytest -n4 test/tests
