name: Run Azure DevOps pipeline on PR comment command

on:
  pull_request:
    types: [closed]

env:
  AZ_DEVOPS_PROJECT_URL: https://dev.azure.com/stankevychvladyslav/test_project
  AZ_DEVOPS_PIPELINE_NAME: "New test pipeline"

jobs:
  pr_is_closed:
    # This job only runs for pull request comments
    name: Delete resources created with the merged/closed branch
    runs-on: ubuntu-latest
    steps:
    # Do not remove: useful for debug purposes
    - name: Dump event JSON and environment
      run: cat "$GITHUB_EVENT_PATH"; env

    - uses: actions/checkout@v3
      with:
        ref: main

    - uses: Azure/pipelines@v1.2
      with:
        azure-devops-project-url: '${{ env.AZ_DEVOPS_PROJECT_URL }}'
        azure-pipeline-name: '${{ env.AZ_DEVOPS_PIPELINE_NAME }}' # name of the Azure pipeline to be triggere
        azure-devops-token: '${{ secrets.AZURE_DEVOPS_TOKEN }}'
        azure-pipeline-variables:  '{"source_branch": "${{ github.event.pull_request.head.ref }}"}' # optional stringified json