name: Run on PR comment

on: 
  issue_comment:
    types: [created]

jobs:
  pr_commented:
    # This job only runs for pull request comments
    name: PR comment
    if: ${{ github.event.issue.pull_request }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Echo PR comment
      run: |
        echo "${{ github.event.comment.body }}"
        echo "${{ github.ref }}"
        echo "${{ github.event.pull_request.head.sha }}"
        cat Dockerfile

    - name: Checkout Pull Request
      run: hub pr checkout ${{ github.event.issue.number }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Echo PR comment
      run: |
        echo "${{ github.event.comment.body }}"
        echo "${{ github.ref }}"
        echo "${{ github.base_ref }}"

    - name: Azure Pipelines Action
      uses: Azure/pipelines@v1.2
      with:
        azure-devops-project-url: https://dev.azure.com/stankevychvladyslav/test_project
        azure-pipeline-name: 'Test_pipeline'
        azure-devops-token: ${{ secrets.AZURE_DEVOPS_TOKEN }}
        azure-pipeline-variables:  '{"check_if_works": "IT WORKS"}'
        
#    - name: Set up Python 3.10
#      uses: actions/setup-python@v2
#      with:
#        python-version: 3.10
#    - name: Add conda to system path
#      run: |
#        # $CONDA is an environment variable pointing to the root of the miniconda directory
#        echo $CONDA/bin >> $GITHUB_PATH
#    - name: Install dependencies
#      run: |
#        conda env update --file environment.yml --name base
