name: Run on PR comment

on:
  issue_comment:
    types: [created]

jobs:
  pr_commented:
    # This job only runs for pull request comments
    name: PR comment
    if: ${{ github.event.issue.pull_request }}
    runs-on: ubuntu-latest
    steps:
    - name: get pull request ref
      id: get_pull_request_ref
      uses: octokit/request-action@v2.x
      with:
        route: GET /repos/:repository/pulls/:issue_id
        repository: ${{ github.repository }}
        issue_id: ${{ github.event.issue.number }}
      env:
        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        
    - uses: actions/checkout@v2
      with:
        ref: ${{ fromJson(steps.get_pull_request_ref.outputs.data).head.ref }}
        fetch-depth: 0

    - name: Echo PR comment
      run: |
        echo "---------"
        echo "lola=lolita" >> $GITHUB_ENV
        echo $lola
        # echo $GITHUB_REF
        # echo $GITHUB_SHA
        # echo 'GITHUB_REF="refs/heads/${{ fromJson(steps.get_pull_request_ref.outputs.data).head.ref }}"' >> $GITHUB_ENV
        # echo 'GITHUB_SHA=${{ fromJson(steps.get_pull_request_ref.outputs.data).head.sha }}' >> $GITHUB_ENV
        echo "---------"
        echo ${{ fromJson(steps.get_pull_request_ref.outputs.data).head.ref }}
        echo ${{ fromJson(steps.get_pull_request_ref.outputs.data).head.sha }}
        echo "---------"
        # echo "${{ github.event.comment.body }}"
        # echo "${{ github.ref }}"
        # git branch
        
    - name: Echo updated variables
      run: |
        echo "---------"
        echo $lola
        echo "---------"
        env

#    - name: Checkout Pull Request
#      run: hub pr checkout ${{ github.event.issue.number }}
#      env:
#        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#        
#    - name: Echo PR comment
#      run: |
#        echo "${{ github.event.comment.body }}"
#        echo "${{ github.ref }}"
#        echo "${{ github.base_ref }}"

    - name: Azure Pipelines Action
      uses: Azure/pipelines@v1.2
      with:
        azure-devops-project-url: https://dev.azure.com/stankevychvladyslav/test_project
        azure-pipeline-name: 'Test_pipeline'
        azure-devops-token: ${{ secrets.AZURE_DEVOPS_TOKEN }}
        azure-pipeline-variables:  '{"check_if_works": "IT WORKS"}'
        
#    - name: Set up Python 3.10
#      uses: actions/setup-python@v2
#      with:
#        python-version: 3.10
#    - name: Add conda to system path
#      run: |
#        # $CONDA is an environment variable pointing to the root of the miniconda directory
#        echo $CONDA/bin >> $GITHUB_PATH
#    - name: Install dependencies
#      run: |
#        conda env update --file environment.yml --name base
